const images=[
    {id:0,name:'St.Xaviers Collage,Mumbai',image:'https://www.storypick.com/wp-content/uploads/2017/03/colg.jpg',state:'Mumbai',des:`St. Xavier’s College, Mumbai, founded on January 2, 1869, is a prestigious private Catholic institution affiliated with the University of Mumbai. Managed by the Bombay Province of the Society of Jesus (Jesuits), it is named after St. Francis Xavier, a 16th-century Spanish missionary. The college is celebrated for its academic excellence, vibrant campus life, and emphasis on holistic education. In 2010, it became the first college under the University of Mumbai to receive autonomous status, granting it greater freedom in designing its curriculum while maintaining high academic standards.`},
    
    {id:1,name:'Amity University, Noida ',image:'https://www.bbacollegesindia.in/wp-content/uploads/2017/03/Amity-Business-School-Noida-1024x489.jpg',state:'Noida',des:`Amity University, Noida, established in 2005 by the Ritnand Balved Education Foundation, is a leading private research university located in Noida, Uttar Pradesh. Recognized by the University Grants Commission (UGC) and the All India Council for Technical Education (AICTE), it holds an 'A+' accreditation from the National Assessment and Accreditation Council (NAAC) . The university is also accredited by the Western Association of Schools and Colleges (WASC) .​
Wikipedia
Careers360

The 60-acre urban campus offers a diverse range of undergraduate, postgraduate, and doctoral programs across various disciplines, including engineering, management, law, biotechnology, and liberal arts. With a student population of over 35,000 and an academic staff of more than 2,200, Amity emphasizes a blend of academic rigor and practical experience .`},
    {id:2,name:'Indian institute of technology delhi',image:'http://home.iitd.ac.in/images/for-faculty/camp8.jpg',state:'Delhi',des:`​The Indian Institute of Technology Delhi (IIT Delhi), established in 1961, is one of India's premier public engineering institutions. Recognized as an Institute of National Importance, it has been a cornerstone in advancing science, engineering, and technology education and research in the country. ​
Wikipedia

Located in the Hauz Khas area of South Delhi, the main campus spans over 320 acres and is surrounded by historical landmarks like the Qutb Minar and the Lotus Temple. The campus is divided into zones for academics, student residences, faculty housing, and recreational activities, featuring facilities such as the Student Activity Center, sports complexes, and 14 hostels named after Indian mountain ranges. `},
    {id:3,name:'AIIMS Delhi',image:'https://cdn.zeebiz.com/sites/default/files/2022/11/30/213666-screenshot-2022-11-30-174545.jpg',state:'Delhi',des:`The All India Institute of Medical Sciences (AIIMS), New Delhi, established in 1956, is a premier public medical university and hospital in India. Recognized as an Institute of National Importance, AIIMS operates autonomously under the Ministry of Health and Family Welfare. Its mission encompasses developing high standards of medical education, research, and patient care. ​


Situated in Ansari Nagar, South Delhi, the main campus spans over 213 acres and includes multiple specialized centers such as the Cardiothoracic and Neurosciences Centre, Dr. Rajendra Prasad Centre for Ophthalmic Sciences, and the Dr. B.R. Ambedkar Institute Rotary Cancer Hospital. Additional campuses include the Jai Prakash Narayan Apex Trauma Centre, the Masjid Moth Campus, and the Ayurvigyan Nagar Campus. AIIMS also has extension campuses in Jhajjar, Haryana, and Ballabhgarh, Faridabad, focusing on specialized research and rural health services, respectively`},
    {id:4,name:'Galgoties University Delhi',image:'https://galgotiauniversityreviews.weebly.com/uploads/9/5/7/7/95772570/galgotia-university12.jpg',state:'Noida',des:`​Galgotias University, established in 2011, is a prominent private institution located in Greater Noida, Uttar Pradesh. Recognized by the University Grants Commission (UGC), the university has rapidly gained a reputation for academic excellence and industry-oriented education. It holds an 'A+' accreditation from the National Assessment and Accreditation Council (NAAC), reflecting its commitment to high educational standards .​
Shiksha

The university's expansive 52-acre urban campus offers a dynamic environment for over 30,000 students. With a legacy spanning more than two decades, Galgotias University has garnered over 300 awards and has collaborations with more than 1,200 companies, enhancing its emphasis on research, innovation, and industry integration .​`},
    {id:5,name:'BITS Pilani Hydrabad',image:'https://www.catalyser.in/public/img/blog/bits2.jpg',state:'Hydrabad',des:`The Birla Institute of Technology and Science, Pilani (BITS Pilani), established in 1964, is a premier private deemed university in India, recognized as an Institute of Eminence by the Ministry of Education. Founded by industrialist G.D. Birla, the institute's motto, "Gyanam Paramam Balam" (Knowledge is Supreme Power), reflects its commitment to excellence in education and research.​
Situated in Pilani, Rajasthan, the main campus spans 328 acres and features state-of-the-art academic buildings, laboratories, and residential facilities. The campus also houses the Birla Museum and the Sharda Peeth temple, adding cultural and historical significance to the institution`},
    {id:6,name:'Netaji Subhash Institute of Technology Delhi',image:'https://www.newsilike.in/wp-content/uploads/NSIT-1280x720.png',state:'Delhi',des:`Netaji Subhas Institute of Technology (NSIT), Bihta, established in 2007, is a private engineering college located in Bihta, Patna, Bihar. The institute commenced its first academic session in 2008 and has since developed a substantial campus spanning approximately 18 acres with over 400,000 square feet of built-up area .​
nsit.in

NSIT Bihta offers a range of undergraduate programs, including Bachelor of Technology (B.Tech) degrees in disciplines such as Electrical & Electronics Engineering, Computer Engineering, Electronics & Communication Engineering, Mechanical Engineering, and Civil Engineering. Additionally, the institute provides diploma courses in fields like Mechanical Engineering, Electrical & Electronics Engineering, Civil Engineering, Electrical Engineering, and Computer Science and Engineering. These programs are affiliated with Bihar Engineering University and the State Board of Technical Education`},
   

]

export default images;
