
const images=[
    {id:'0',name:'Mumbai',state:'Maharashtra',image:'https://cdn.i-scmp.com/sites/default/files/d8/images/canvas/2024/10/01/d7d1c597-84aa-4006-bc28-314639d974c2_69852536.jpg',des:`Mumbai, often hailed as the "Financial Capital of India," stands as a dynamic and powerful economic center, not just for the country but increasingly for the world. Sitting along the Arabian Sea, this sprawling metropolis pulses with commercial energy. It is home to India's most important financial institutions, including the Reserve Bank of India, Bombay Stock Exchange, and National Stock Exchange, which anchor its status in global finance. Towering corporate headquarters, bustling banks, and busy trading floors drive the city's fast-paced economy, while vibrant industries such as entertainment, media, and fashion add a unique cultural richness that blends seamlessly with its commercial spirit.

The city thrives on an incredibly diverse economy. Its ports, among the busiest in India, handle a massive portion of the country's maritime trade, while its rapidly growing sectors like information technology, real estate, pharmaceuticals, and manufacturing feed into a complex and powerful economic machine. Every day, millions of people — from corporate executives and entrepreneurs to artisans and service workers — contribute to the lifeblood of Mumbai, making it a city of endless opportunity and enterprise.

`},
    {id:'1',name:'Banglore',state:'Karnataka',image:'https://specialplacesofindia.com/wp-content/uploads/2024/01/Untitled-design-2024-06-10T180744.081-1024x512.jpg',des:`Bangalore, officially known as Bengaluru, is often called the "Silicon Valley of India" for its pivotal role in driving the country’s information technology revolution. Located in the southern state of Karnataka, Bangalore sits on the Deccan Plateau and enjoys a moderate, pleasant climate throughout the year, earning it the nickname "Garden City" as well. Over the decades, it has transformed from a quiet, green town into a dynamic metropolis brimming with innovation, technology, and entrepreneurial spirit. The city hosts some of India's largest tech parks, research institutions, and corporate headquarters, attracting talent from across the nation and around the world. Beyond its technological fame, Bangalore is known for its vibrant culture, buzzing nightlife, cosmopolitan crowd, and thriving café and craft beer scenes. Historic landmarks, green spaces like Cubbon Park and Lalbagh Botanical Garden, and a growing arts and music culture weave together the city's old-world charm and modern dynamism. Despite grappling with issues like traffic congestion and rapid urbanization, Bangalore’s youthful energy, openness to new ideas, and drive for progress continue to make it one of India's most exciting and influential cities.`},
    {id:'2',name:'Delhi',state:'Delhi',image:'https://upload.wikimedia.org/wikipedia/commons/4/49/Skyline_at_Rajiv_Chowk.JPG',des:`Delhi, the capital of India, is a city where the ancient and the modern coexist in a vivid tapestry of life. It is a place where centuries-old forts, mosques, and bustling bazaars stand alongside contemporary skyscrapers, luxurious malls, and broad, tree-lined avenues. The city breathes history, from the remnants of mighty empires in Old Delhi to the orderly elegance of New Delhi, a creation of British colonial ambition.

Walking through Delhi, one encounters the grandeur of monuments like the Red Fort and Humayun’s Tomb, while also experiencing the chaotic vibrancy of markets, food stalls, and festivals that reflect India's diversity. The aroma of spices fills the air, mingling with the energy of millions who call this sprawling metropolis home.`},
    {id:'3',name:'Gurugram',state:'Haryana',image:'https://imageproxy-v2.services.lokalebasen.dk/825x500/lb-images-asia/in/1313835/144565-level-11-tower-c-building-no-8-dlf-cyber-city-phase-ii.jpg?v=m1664363520',des:`Gurugram is a major city located in the northern Indian state of Haryana, just southwest of the national capital, New Delhi. It is part of the National Capital Region (NCR) and is one of India’s most prominent financial, industrial, and technology hubs.

Once a quiet agricultural village, Gurugram has rapidly transformed over the past few decades into a bustling metropolis known for its gleaming skyscrapers, luxury shopping malls, high-end residential complexes, and a vibrant corporate sector. Many Fortune 500 companies and major multinational corporations have offices here, particularly in sectors like IT, consulting, finance, and real estate.`},
    {id:'4',name:'Noida',state:'Uttar Pradesh',image:'https://www.financialexpress.com/wp-content/uploads/2024/03/commercial-pix.jpg?w=440',des:`Noida (short for New Okhla Industrial Development Authority) is a well-planned city located in the northern Indian state of Uttar Pradesh, and it is part of the National Capital Region (NCR) surrounding New Delhi. Established in 1976 under the UP Industrial Area Development Act, Noida was developed as a modern industrial and residential hub to support the growing demands of the Delhi metropolitan area.

Today, Noida is recognized for its wide roads, well-organized sectors, abundant green spaces, and rapidly growing urban infrastructure. It is a major center for industries like information technology, business process outsourcing (BPO), media, manufacturing, and real estate.`},
    {id:'5',name:'Hyderabad',state:'Telangana',image:'https://images.yourstory.com/cs/2/21ccd920843c11ec88170b5512a0f9d5/Imageyiut-1671526375707.jpg?mode=crop&crop=faces&ar=2%3A1&format=auto&w=1920&q=75',des:`Hyderabad, the capital of Telangana, has rapidly emerged as one of India's leading economic powerhouses. Traditionally known as the "City of Pearls" for its historic trade in gems and jewelry, the city today is recognized for its dynamic and diversified economy. Hyderabad's transformation is anchored by its booming IT and technology sector, with sprawling tech parks like HITEC City and the Financial District housing global giants such as Microsoft, Google, Amazon, and Facebook. The city is also a major center for the pharmaceutical and biotechnology industries, often referred to as the "Pharma Capital of India," thanks to its concentration of research hubs and industrial parks like Genome Valley. Beyond technology and healthcare, Hyderabad has become a rising star in finance, manufacturing, aerospace, and defense sectors, supported by a business-friendly government and world-class infrastructure`},
    {id:'6',name:'Chennai ',state:'Tamil Nadu',image:`https://www.godrejproperties.com/blog/wp-content/uploads/2023/07/Why-Chennai-has-become-a-key-industrial-hub-in-the-south-1024x333.jpg`,des:`Chennai, the capital of Tamil Nadu, is one of India’s most important cultural, economic, and industrial cities. Located along the southeastern coast by the Bay of Bengal, Chennai combines a deep sense of tradition with a rapidly modernizing economy. Known as the "Detroit of India," the city is a major hub for the automobile industry, housing manufacturing plants for giants like Hyundai, Ford, BMW, and Renault. Beyond automobiles, Chennai has thriving sectors in information technology, healthcare, hardware manufacturing, and financial services. It is also a key center for India's film industry, famously referred to as "Kollywood." The city boasts a robust port, one of the largest in India, which strengthens its status as a major trade and logistics hub. Educational excellence, high-quality medical infrastructure, and a relatively lower cost of living compared to other Indian metros add to its appeal.`},
    {id:'7',name:'Kolkata',state:'West Bengal',image:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUgUwwf8Fm8QPwIN-jadI406-N7vxft8x0Cg&s',des:`Kolkata, the capital of West Bengal, is often called the "Cultural Capital of India", blending colonial-era charm with a vibrant, modern spirit. Situated on the banks of the Hooghly River, the city has a rich historical legacy as a former capital of British India, reflected in its grand architecture, bustling streets, and intellectual atmosphere. Kolkata is a major economic center in eastern India, with key industries including information technology, banking, manufacturing, and port logistics. The city’s economy is anchored by the presence of major corporations, a thriving services sector, and one of India’s busiest ports. Renowned educational institutions, hospitals, and cultural centers contribute to its dynamic character. Kolkata is also famous for its deep connection to art, literature, music, theater, and cinema, making it a hub for creativity and progressive thought. Despite the challenges of urban crowding and aging infrastructure in parts, Kolkata retains a warmth, resilience, and distinctive soul that continue to attract businesses, artists, and visitors alike.`},
]

export default images;